[package]
name = "vTodo"
version = "0.1.0"
authors = ["YT <torshizi1414@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
